---
- name: This is the Ansible script for the control node
  hosts: all
  become: true
  tasks:
    - name: Configure Hosts file on all servers
      template:
        src: hosts.j2
        dest: /etc/hosts
        owner: root
        group: root
        mode: '0644'
    - name: Create user Ender on all nodes.
      user:
        name: Ender
        state: present
    - name: Configure Sudoers file for Ender on all nodes
      copy:
        dest: /etc/sudoers.d/Ender
        content: "Ender ALL=(ALL) NOPASSWD: ALL"
        owner: root
        group: root
    - name: Create the .ssh directory for ssh key to go in.
      file:
        path: /home/Ender/.ssh
        owner: Ender
        group: Ender
        state: directory
    - name: Create SSH keys on Control Node
      openssh_keypair:
        path: /home/Ender/.ssh/id_rsa
