---
- name: In space, no one can hear you scream
  hosts: all
  become: yes
  tasks:
  - name: Deleting Repos Folder and contents thereof
    file:
      path: /etc/yum.repos.d
      state: absent
  - name: Empty shell of a repos folder :(
    file:
      path: /etc/yum.repos.d
      state: directory
  - name: Start of block for vg creation
    block:
      - name: Full partition of second drive
        parted:
          device: /dev/sdb
          number: 1
          part_type: primary
          part_end: 100%
          state: present
      - name: Partprobe
        command: partprobe
      - name: Create VG formics
        lvg:
          vg: formics
          pvs: /dev/sdb1
    when: ansible_facts['devices']['sdb'] is defined
    ignore_errors: true
  
  - name: Remove ansible from Control
    yum:
      name: ansible
      state: absent
      use_backend: YUM4
    when: ansible_hostname == 'control'
  - name: Add /etc/hosts file to control
    template:
      src: hosts.j2
      dest: /etc/hosts
    when: ansible_hostname == 'control'
