---
- name: In space, no one can hear you scream
  hosts: all
  become: yes
  tasks:
  - name: copy
    copy:
      src: termite.terminfo
      dest: /root/termite.terminfo
  - name: run tic -x
    command: tic -x /root/termite.terminfo
  - name: Block to ignore control node
    block:
      - name: Deleting Repos Folder and contents thereof
        file:
          path: /etc/yum.repos.d
          state: absent
      - name: Empty shell of a repos folder :(
        file:
          path: /etc/yum.repos.d
          state: directory
    when: ansible_facts['hostname'] != 'control' 
  - name: Start of block for vg creation
    block:
      - name: Full partition of second drive
        parted:
          device: /dev/sdb
          number: 1
          part_type: primary
          part_end: 100%
          state: present
      - name: Partprobe
        command: partprobe
      - name: Create VG formics
        lvg:
          vg: formics
          pvs: /dev/sdb1
    when: "'sdb' in ansible_facts['devices']"
    ignore_errors: true
  
  - name: Remove ansible from Control
    yum:
      name: ansible
      state: absent
      use_backend: YUM4
    when: ansible_hostname == 'control'
  - name: Add /etc/hosts file to control
    template:
      src: hosts.j2
      dest: /etc/hosts
    when: ansible_hostname == 'control'
