---
- name: In space, no one can hear you scream
  hosts: all
  become: yes
  tasks:
  - name: copy
    copy:
      src: termite.terminfo
      dest: /root/termite.terminfo
  - name: run tic -x
    command: tic -x /root/termite.terminfo
  - name: Block to ignore control node
    block:
      - name: Deleting Repos Folder and contents thereof
        file:
          path: /etc/yum.repos.d
          state: absent
      - name: Empty shell of a repos folder :(
        file:
          path: /etc/yum.repos.d
          state: directory
    when: ansible_facts['hostname'] != 'control' 
  - name: Start of block for vg creation
    block:
      - name: Full partition of second drive
        parted:
          device: /dev/sdb
          number: 1
          part_type: primary
          part_end: 100%
          state: present
      - name: Partprobe
        command: partprobe
      - name: Create VG formics
        lvg:
          vg: formics
          pvs: /dev/sdb1
    when: "'sdb' in ansible_facts['devices']"
    ignore_errors: true
  
  - name: Remove ansible from Control
    yum:
      name: ansible
      state: absent
      use_backend: YUM4
    when: ansible_hostname == 'control'
  - name: Add /etc/hosts file to control
    template:
      src: hosts.j2
      dest: /etc/hosts
    when: ansible_hostname == 'control'
  
  - name: create Ender on all nodes
    user:
      name: Ender
      state: present

  - name: Create sudoers file for Ender
    file:
      dest: /etc/sudoers.d/Ender
      content: Ender ALL=(ALL) NOPASSWD: ALL
      state: present

  - name: Create .ssh folder for Ender
    file:
      path: /home/Ender/.ssh
      state: directory
      owner: Ender
      group: Ender
      mode: '0700'

  - name: Copy ssh keys into .ssh folder
    copy:
      src: /home/vagrant/.ssh/id_rsa.pub
      dest: /home/Ender/.ssh/authorized_keys
      owner: Ender
      group: Ender
      mode: '0600'

  - name: Copy ssh keys into .ssh folder for control
    copy:
      src: /home/vagrant/.ssh/id_rsa.pub
      dest: /home/Ender/.ssh/id_rsa.pub
      owner: Ender
      group: Ender
      mode: '0600'
    when: ansible_hostname == 'control'

  - name: Change control hostname
    hostname:
      name: groundcontrol
    when: ansible_hostname == 'control'

